### ISSUE TITLE
Questions about training frame rate and training time

### ISSUE THREAD

**Issue by peakfly** [jzhzhang/3DAwareNav#4]
This algorithm can only run 2-3 frames when I run the "sh_train.sh".However,the paper says the algorithm can run 15 frames.It takes a long time to train.The code runs on run on a workstation with an Intel(R) Xeon(R) Gold 6226R CPU with 256GB RAM and 2 Nvidia RTX3090 GPUs with 24GB memory.The "sh_train.sh" is as follows:
```
export GLOG_minloglevel=2
export MAGNUM_LOG="quiet"

python main.py --auto_gpu_config 0  -n 8 --num_training_frames 1000000\
    --sem_gpu_id_list "3"  --policy_gpu_id "cuda:4"  --sim_gpu_id "4" \
    --split train  --backbone_2d "rednet"  \
    --task_config "tasks/challenge_objectnav2021.local.rgbd.yaml"  --dataset "mp3d" \
    --num_sem_categories 22 --deactivate_entropymap \
    --print_images 1  -d ./tmp  --exp_name exp_kl_goal1  --save_periodic 10000 
``` 
![image](https://github.com/jzhzhang/3DAwareNav/assets/68849846/f6796efd-851a-4be8-8ffe-92aeaa32242c)

**Comment by jzhzhang** [comment]
During training, there are lots of operations including rollout storage and backward finetuning. 

In our paper, we report the reconstruction performance, which only measures the construction time. If you want more higher FPS (like close to real-time) in construction time, you can simply downsample the per-frame point cloud (It's doable because of significant overlap).

**Comment by peakfly** [comment]
您的邮件已收到！谢谢！--------------------------------------------This is an automatic reply, confirming that your e-mail was received.Thank you
